* Contrast is defined as being in a 'strikingly' different state from something else.
* WCAG (Web Content Accessibility Guilines) 2.0 (Making sure our stuff is accessible to those with vision impairment issues):
 - (Minimum AA) The visual representation of text and images of text has a contrast ratio of at least 4.5:1,
    except for large text which should have a contrast ratio of at least 3:1.
 - (Enhanced AAA) The visual representation of text and images of text has a contrast ratio of at least 7:1, 
    except for large text which should have a contrast ratio of at least 4.5:1.
* How do I know if my elements are contrasting? We can search for WCAG pluging for Chrome. Sketch/Figma applications.
